### ISSUE TITLE
Add additional plots

### ISSUE THREAD

**Issue by DrPaulSharp** [RascalSoftware/python-RAT#45]
We have a plotting module that contains a plotting figure class and the `plot_ref_sld` routine. We want to add the following, adapted from the MATLAB code:

- [x] `cornerPlot`
- [x] `plotHists`
- [x] `bayesShadedPlot`
- [x] `histp`
- [x] `mcmcplot`
- [x] ~~`shade`~~
- [x] `plotBayes` (this function simply calls other plotting functions)

**Comment by DrPaulSharp** [comment]
Note - Bear in mind that some of these plots require Bayesian analysis. To get this data, run either the "NS" or "Dream" minimisers.

**Comment by alexhroom** [comment]
`shade` is not required as its function is covered by `plt.fill_between`
